// Common
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_CURRENT_BLOCK_NUMBER = "UPDATE_CURRENT_BLOCK_NUMBER";
export const UPDATE_ACCOUNT_BALANCE = "UPDATE_ACCOUNT_BALANCE";

// Authentication
export const AUTHENTICATION = "AUTHENTICATION";
export const AUTHENTICATION_ADMINS = "AUTHENTICATION_ADMINS";
export const AUTHENTICATION_STORE_OWNERS = "AUTHENTICATION_STORE_OWNERS";
export const AUTHENTICATION_ADMIN_ADDED_EVENT =
  "AUTHENTICATION_ADMIN_ADDED_EVENT";
export const AUTHENTICATION_STORE_OWNER_ADDED_EVENT =
  "AUTHENTICATION_STORE_OWNER_ADDED_EVENT";
export const AUTHENTICATION_ADMIN_REMOVED_EVENT =
  "AUTHENTICATION_ADMIN_REMOVED_EVENT";
export const AUTHENTICATION_STORE_OWNER_REMOVED_EVENT =
  "AUTHENTICATION_STORE_OWNER_REMOVED_EVENT";

// Marketplace
export const MARKETPLACE_CURRENT_STORE = "MARKETPLACE_CURRENT_STORE";
export const MARKETPLACE_STORES = "MARKETPLACE_STORES";
export const MARKETPLACE_ITEMS = "MARKETPLACE_ITEMS";
export const MARKETPLACE_ITEM_REMOVED_EVENT = "MARKETPLACE_ITEM_REMOVED_EVENT";
export const MARKETPLACE_ITEMS_TO_SHIP = "MARKETPLACE_ITEMS_TO_SHIP";
export const MARKETPLACE_ITEMS_TO_RECEIVE = "MARKETPLACE_ITEMS_TO_RECEIVE";
